/**
 * Stage definitions for each worker.
 * Shared across C2 console and campaign overview pages.
 *
 * `stageName` matches the pipeline stage name used in playbook configs.
 * `name` is the human-readable display name.
 */
export const WORKER_STAGES: Record<string, { id: string; name: string; stageName: string; sectionId: string }[]> = {
  info_gathering: [
    { id: "1", name: "Search Engine Discovery", stageName: "search_engine_recon", sectionId: "WSTG-INFO-01" },
    { id: "2", name: "Fingerprint Web Server", stageName: "web_server_fingerprint", sectionId: "WSTG-INFO-02" },
    { id: "3", name: "Review Webserver Metafiles", stageName: "web_server_metafiles", sectionId: "WSTG-INFO-03" },
    { id: "4", name: "Enumerate Applications", stageName: "enumerate_applications", sectionId: "WSTG-INFO-04" },
    { id: "5", name: "Review Comments", stageName: "review_comments", sectionId: "WSTG-INFO-05" },
    { id: "6", name: "Review Comments (Deep)", stageName: "review_comments_deep", sectionId: "WSTG-INFO-05" },
    { id: "7", name: "Identify Entry Points", stageName: "identify_entry_points", sectionId: "WSTG-INFO-06" },
    { id: "8", name: "Map Execution Paths", stageName: "map_execution_paths", sectionId: "WSTG-INFO-07" },
    { id: "9", name: "Fingerprint Framework", stageName: "fingerprint_framework", sectionId: "WSTG-INFO-08" },
    { id: "10", name: "Map Architecture", stageName: "map_architecture", sectionId: "WSTG-INFO-09" },
    { id: "11", name: "Map Application", stageName: "map_application", sectionId: "WSTG-INFO-10" },
  ],
  config_mgmt: [
    { id: "1", name: "Network Configuration", stageName: "network_config", sectionId: "WSTG-CONF-01" },
    { id: "2", name: "Platform Configuration", stageName: "platform_config", sectionId: "WSTG-CONF-02" },
    { id: "3", name: "File Extension Handling", stageName: "file_extension_handling", sectionId: "WSTG-CONF-03" },
    { id: "4", name: "Backup Files", stageName: "backup_files", sectionId: "WSTG-CONF-04" },
    { id: "5", name: "API Discovery", stageName: "api_discovery", sectionId: "WSTG-CONF-05" },
    { id: "6", name: "HTTP Methods", stageName: "http_methods", sectionId: "WSTG-CONF-06" },
    { id: "7", name: "HTTP Strict Transport Security", stageName: "hsts_testing", sectionId: "WSTG-CONF-07" },
    { id: "8", name: "RPC Testing", stageName: "rpc_testing", sectionId: "WSTG-CONF-08" },
    { id: "9", name: "File Inclusion", stageName: "file_inclusion", sectionId: "WSTG-CONF-09" },
    { id: "10", name: "Subdomain Takeover", stageName: "subdomain_takeover", sectionId: "WSTG-CONF-10" },
    { id: "11", name: "Cloud Storage", stageName: "cloud_storage", sectionId: "WSTG-CONF-11" },
  ],
  identity_mgmt: [
    { id: "1", name: "Role Definitions", stageName: "role_definitions", sectionId: "WSTG-IDNT-01" },
    { id: "2", name: "Registration Process", stageName: "registration_process", sectionId: "WSTG-IDNT-02" },
    { id: "3", name: "Account Provisioning", stageName: "account_provisioning", sectionId: "WSTG-IDNT-03" },
    { id: "4", name: "Account Enumeration", stageName: "account_enumeration", sectionId: "WSTG-IDNT-04" },
    { id: "5", name: "Weak Username Policy", stageName: "weak_username_policy", sectionId: "WSTG-IDNT-05" },
  ],
  authentication: [
    { id: "1", name: "Credentials Transported over Unencrypted Channel", stageName: "credentials_transport", sectionId: "WSTG-ATHN-01" },
    { id: "2", name: "Default Credentials", stageName: "default_credentials", sectionId: "WSTG-ATHN-02" },
    { id: "3", name: "Weak Lock Out Mechanism", stageName: "lockout_mechanism", sectionId: "WSTG-ATHN-03" },
    { id: "4", name: "Authentication Bypass", stageName: "auth_bypass", sectionId: "WSTG-ATHN-04" },
    { id: "5", name: "Vulnerable Remember Password", stageName: "remember_password", sectionId: "WSTG-ATHN-05" },
    { id: "6", name: "Browser Cache Weaknesses", stageName: "browser_cache", sectionId: "WSTG-ATHN-06" },
    { id: "7", name: "Weak Password Policy", stageName: "weak_password_policy", sectionId: "WSTG-ATHN-07" },
    { id: "8", name: "Security Questions", stageName: "security_questions", sectionId: "WSTG-ATHN-08" },
    { id: "9", name: "Password Change", stageName: "password_change", sectionId: "WSTG-ATHN-09" },
    { id: "10", name: "Multi-Channel Authentication", stageName: "multi_channel_auth", sectionId: "WSTG-ATHN-10" },
  ],
  authorization: [
    { id: "1", name: "Directory Traversal", stageName: "directory_traversal", sectionId: "WSTG-ATHZ-01" },
    { id: "2", name: "Bypass Authorization Schema", stageName: "authz_bypass", sectionId: "WSTG-ATHZ-02" },
    { id: "3", name: "Privilege Escalation", stageName: "privilege_escalation", sectionId: "WSTG-ATHZ-03" },
    { id: "4", name: "Insecure Direct Object Reference", stageName: "idor", sectionId: "WSTG-ATHZ-04" },
  ],
  session_mgmt: [
    { id: "1", name: "Session Management Schema", stageName: "session_scheme", sectionId: "WSTG-SESS-01" },
    { id: "2", name: "Cookie Attributes", stageName: "cookie_attributes", sectionId: "WSTG-SESS-02" },
    { id: "3", name: "Session Fixation", stageName: "session_fixation", sectionId: "WSTG-SESS-03" },
    { id: "4", name: "Exposed Session Variable", stageName: "exposed_variables", sectionId: "WSTG-SESS-04" },
    { id: "5", name: "Cross Site Request Forgery", stageName: "csrf", sectionId: "WSTG-SESS-05" },
    { id: "6", name: "Logout Functionality", stageName: "logout_functionality", sectionId: "WSTG-SESS-06" },
    { id: "7", name: "Session Timeout", stageName: "session_timeout", sectionId: "WSTG-SESS-07" },
    { id: "8", name: "Session Puzzling", stageName: "session_puzzling", sectionId: "WSTG-SESS-08" },
    { id: "9", name: "Session Hijacking", stageName: "session_hijacking", sectionId: "WSTG-SESS-09" },
  ],
  input_validation: [
    { id: "1", name: "Reflected Cross Site Scripting", stageName: "reflected_xss", sectionId: "WSTG-INPV-01" },
    { id: "2", name: "Stored Cross Site Scripting", stageName: "stored_xss", sectionId: "WSTG-INPV-02" },
    { id: "3", name: "HTTP Verb Tampering", stageName: "http_verb_tampering", sectionId: "WSTG-INPV-03" },
    { id: "4", name: "HTTP Parameter Pollution", stageName: "http_param_pollution", sectionId: "WSTG-INPV-04" },
    { id: "5", name: "SQL Injection", stageName: "sql_injection", sectionId: "WSTG-INPV-05" },
    { id: "6", name: "LDAP Injection", stageName: "ldap_injection", sectionId: "WSTG-INPV-06" },
    { id: "7", name: "XML Injection", stageName: "xml_injection", sectionId: "WSTG-INPV-07" },
    { id: "8", name: "Server-Side Template Injection", stageName: "ssti", sectionId: "WSTG-INPV-08" },
    { id: "9", name: "XPath Injection", stageName: "xpath_injection", sectionId: "WSTG-INPV-09" },
    { id: "10", name: "IMAP/SMTP Injection", stageName: "imap_smtp_injection", sectionId: "WSTG-INPV-10" },
    { id: "11", name: "Code Injection", stageName: "code_injection", sectionId: "WSTG-INPV-11" },
    { id: "12", name: "Command Injection", stageName: "command_injection", sectionId: "WSTG-INPV-12" },
    { id: "13", name: "Format String", stageName: "format_string", sectionId: "WSTG-INPV-13" },
    { id: "14", name: "Host Header Injection", stageName: "host_header_injection", sectionId: "WSTG-INPV-14" },
    { id: "15", name: "Server-Side Request Forgery", stageName: "ssrf", sectionId: "WSTG-INPV-15" },
    { id: "16", name: "File Inclusion", stageName: "file_inclusion", sectionId: "WSTG-INPV-16" },
    { id: "17", name: "Buffer Overflow", stageName: "buffer_overflow", sectionId: "WSTG-INPV-17" },
    { id: "18", name: "HTTP Smuggling", stageName: "http_smuggling", sectionId: "WSTG-INPV-18" },
    { id: "19", name: "WebSocket Injection", stageName: "websocket_injection", sectionId: "WSTG-INPV-19" },
  ],
  error_handling: [
    { id: "1", name: "Improper Error Handling", stageName: "error_codes", sectionId: "WSTG-ERRH-01" },
    { id: "2", name: "Stack Trace", stageName: "stack_traces", sectionId: "WSTG-ERRH-02" },
  ],
  cryptography: [
    { id: "1", name: "Weak Transport Layer Security", stageName: "tls_testing", sectionId: "WSTG-CRYP-01" },
    { id: "2", name: "Padding Oracle", stageName: "padding_oracle", sectionId: "WSTG-CRYP-02" },
    { id: "3", name: "Sensitive Information Sent via Unencrypted Channels", stageName: "plaintext_transmission", sectionId: "WSTG-CRYP-03" },
    { id: "4", name: "Weak Encryption", stageName: "weak_crypto", sectionId: "WSTG-CRYP-04" },
  ],
  business_logic: [
    { id: "1", name: "Data Validation", stageName: "data_validation", sectionId: "WSTG-BUSL-01" },
    { id: "2", name: "Request Forgery", stageName: "request_forgery", sectionId: "WSTG-BUSL-02" },
    { id: "3", name: "Integrity Checks", stageName: "integrity_checks", sectionId: "WSTG-BUSL-03" },
    { id: "4", name: "Process Timing", stageName: "process_timing", sectionId: "WSTG-BUSL-04" },
    { id: "5", name: "Rate Limiting", stageName: "rate_limiting", sectionId: "WSTG-BUSL-05" },
    { id: "6", name: "Workflow Bypass", stageName: "workflow_bypass", sectionId: "WSTG-BUSL-06" },
    { id: "7", name: "Application Misuse", stageName: "application_misuse", sectionId: "WSTG-BUSL-07" },
    { id: "8", name: "File Upload Validation", stageName: "file_upload_validation", sectionId: "WSTG-BUSL-08" },
    { id: "9", name: "Malicious File Upload", stageName: "malicious_file_upload", sectionId: "WSTG-BUSL-09" },
  ],
  client_side: [
    { id: "1", name: "DOM-Based XSS", stageName: "dom_xss", sectionId: "WSTG-CLNT-01" },
    { id: "2", name: "Clickjacking", stageName: "clickjacking", sectionId: "WSTG-CLNT-02" },
    { id: "3", name: "CSRF Tokens", stageName: "csrf_tokens", sectionId: "WSTG-CLNT-03" },
    { id: "4", name: "CSP Bypass", stageName: "csp_bypass", sectionId: "WSTG-CLNT-04" },
    { id: "5", name: "HTML5 Injection", stageName: "html5_injection", sectionId: "WSTG-CLNT-05" },
    { id: "6", name: "Web Storage", stageName: "web_storage", sectionId: "WSTG-CLNT-06" },
    { id: "7", name: "Client-Side Logic", stageName: "client_side_logic", sectionId: "WSTG-CLNT-07" },
    { id: "8", name: "DOM-Based Injection", stageName: "dom_based_injection", sectionId: "WSTG-CLNT-08" },
    { id: "9", name: "Client-Side Resource Manipulation", stageName: "client_side_resource_manipulation", sectionId: "WSTG-CLNT-09" },
    { id: "10", name: "Client-Side Auth", stageName: "client_side_auth", sectionId: "WSTG-CLNT-10" },
    { id: "11", name: "Cross Site Scripting (Client)", stageName: "xss_client_side", sectionId: "WSTG-CLNT-11" },
    { id: "12", name: "CSS Injection", stageName: "css_injection", sectionId: "WSTG-CLNT-12" },
    { id: "13", name: "Malicious Upload (Client)", stageName: "malicious_upload_client", sectionId: "WSTG-CLNT-13" },
  ],
  mobile_worker: [
    { id: "1", name: "Acquire & Decompile", stageName: "acquire_decompile", sectionId: "MOBILE-01" },
    { id: "2", name: "Secret Extraction", stageName: "secret_extraction", sectionId: "MOBILE-02" },
    { id: "3", name: "Configuration Audit", stageName: "configuration_audit", sectionId: "MOBILE-03" },
    { id: "4", name: "Dynamic Analysis", stageName: "dynamic_analysis", sectionId: "MOBILE-04" },
    { id: "5", name: "Endpoint Feedback", stageName: "endpoint_feedback", sectionId: "MOBILE-05" },
  ],
  reasoning_worker: [
    { id: "1", name: "Finding Correlation", stageName: "finding_correlation", sectionId: "REASON-01" },
    { id: "2", name: "Impact Analysis", stageName: "impact_analysis", sectionId: "REASON-02" },
    { id: "3", name: "Chain Hypothesis", stageName: "chain_hypothesis", sectionId: "REASON-03" },
  ],
  chain_worker: [
    { id: "1", name: "Data Collection", stageName: "data_collection", sectionId: "CHAIN-01" },
    { id: "2", name: "Chain Evaluation", stageName: "chain_evaluation", sectionId: "CHAIN-02" },
    { id: "3", name: "AI Chain Discovery", stageName: "ai_chain_discovery", sectionId: "CHAIN-03" },
    { id: "4", name: "Chain Execution", stageName: "chain_execution", sectionId: "CHAIN-04" },
    { id: "5", name: "Reporting", stageName: "reporting", sectionId: "CHAIN-05" },
  ],
  reporting: [
    { id: "1", name: "Data Gathering", stageName: "data_gathering", sectionId: "RPT-01" },
    { id: "2", name: "Deduplication", stageName: "deduplication", sectionId: "RPT-02" },
    { id: "3", name: "Rendering", stageName: "rendering", sectionId: "RPT-03" },
    { id: "4", name: "Export", stageName: "export", sectionId: "RPT-04" },
  ],
  proxy: [],
  callback: [],
  sandbox_worker: [],
};
